version: '3.8'

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"