# APP
server.port=${SERVER_PORT}
spring.application.name=fretenetapi

# REDIS CACHE
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.cache.redis.cache-null-values=false

# RABBITMQ MESSAGING
spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=${RABBIT_PORT}
spring.rabbitmq.username=${RABBIT_USERNAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}
spring.rabbitmq.listener.time-retry=${RABBIT_TIME_RETRY}
spring.rabbitmq.request.exchange.producer=direct.exchange
spring.rabbitmq.request.routing-key.producer=fila.principal
spring.rabbitmq.request.dead-letter.producer=fila.retentativa
spring.rabbitmq.request.parking-lot.producer=fila.erro

# MONGODB DATABASE
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=${MONGODB_URI}